logging:
  level:
      com.hc: debug
  file: ./log/vertx.log
  root: DEBUG
hc:
  commons:
    artifactId: wriststrap  
    instanceId: wriststrap_1 #集群节点名，部署时注意要唯一
    host: 0.0.0.0
    tcpPort: 8765
    callbackDomain: https://hctest.hushijie.com.cn
    maxBusBlockingTime: 1500
    eventBusThreadNumber: 100
    eventBusQueueSize: 1

#配置中心配置项
#callbackDomain
#instanceNumber
