server:
  #http服务端口
  port: 8766
logging:
  level:
      com.hc: debug
  file: ./log/vertx.log
  root: DEBUG
hc:
  commons:
    basePath: com.hc.equipment.controller
    controllerPath:
      - com.hc.equipment.tcp.WriststrapTCPController
      - com.hc.equipment.http.WriststrapHTTPController
    host: 0.0.0.0
    tcpPort: 8765
    httpPort: 8766
    callbackDomain: https://hcadmin.hushijie.com.cn
    maxHTTPIdleTime: 4