logging:
  level:
      com.hc: debug
  file: ./log/vertx.log
connector:
  commons:
    nodeArtifactId: wriststrap_1
    equipmentType: 1
    protocol: 0
    host: 0.0.0.0
    tcpPort: 8765
    defaultTimeout: 6000
    maxBusBlockingTime: 5000
    eventBusQueueSize: 100
    tcpTimeout: 3000000
  rabbitmq:
    mqHost: localhost
    mqPort: 5672
    mqUserName: admin
    mqPwd: 12345678
    virtualHost: /
    upQueueName: upstream
    downQueueName: wriststrap
    exchangeName: device_communication
