logging:
  level:
      com.hc: debug
  file: ./log/vertx.log
connector:
  commons:
    nodeArtifactId: wriststrap_1
    equipmentType: 0
    protocol: 0
    host: 0.0.0.0
    tcpPort: 8765
    defaultTimeout: 6000
    maxBusBlockingTime: 50000
    eventBusQueueSize: 100
    timeout: 100000
    timeDisconnect: 180000
    tcpTimeout: 120000
  rabbitmq:
    mqHost: 39.105.125.26
    mqPort: 5672
    mqUserName: admin
    mqPwd: 12345678
    virtualHost: /
    upQueueName: upstream
    downQueueName: wriststrap
    exchangeName: device_communication
